//window.alert("Dobro dosli");
let x = 3;
console.log("X je jednako " + x);
let carName1 = "Volvo";
let carName2 = 'Golf';
console.log(carName1, carName2);
let answer1 = "It's all alright.";
let answer2 = "He is called 'Johnny'.";
let answer3 = 'He is called "Johnny".';
console.log(answer1);
console.log(answer2);
console.log(answer3);
let age = null;
console.log(age, age + 3);
let firstName = "Pera";
let lastName = " Peric";
let fullName = firstName + lastName;
console.log(fullName);
console.log(fullName.length);
x = 5;
let y = 2;
let z = x + y;
console.log(z);
x *= 5;
console.log(x);
x++;
console.log(x);
z = x % y;
console.log(z);
z = x ** 2;
console.log(z);
x = 16 + "Volvo";
console.log(x);
y = "16" + "Volvo";
console.log(y);
z = 16 + 4 + "Volvo";
console.log(z);
let t = "Volvo" + 16 + 4;
console.log(t);
let p = 5 / "hello";
console.log(p);